### ISSUE TITLE
Nonetype motor status

### ISSUE THREAD

**Issue by parasharmohapatra** [axiondarkmatterexperiment/dripline-orpheus#40]
Seemingly randomly, every so often the motor status returns none instead of it's status and I get this error message.

```
root@clerk-dripline-python-deployment-69d7c595c7-sb68g:/usr/local/src/dripline-python-plugin/data_taking_scripts# python move_motors_to_zero.py 
fail!
fail!
Traceback (most recent call last):
  File "move_motors_to_zero.py", line 12, in <module>
    common_functions.wait_for_motors()
  File "/usr/local/src/dripline-python-plugin/data_taking_scripts/common_functions.py", line 38, in wait_for_motors
    while (get_status() != ['R','R','R']):
  File "/usr/local/src/dripline-python-plugin/data_taking_scripts/common_functions.py", line 32, in get_status
    bottom_plate_status = the_interface.get('bottom_dielectric_plate_motor_request_status').payload.to_python()['value_raw']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by raphaelcervantes** [comment]
I think these logs point to the reason why we run into this error. I don't quite know what to do about it yet.

```
2021-08-14T17:44:27[ERROR   ] dripline.implementations.entity_endpoints(139) -> matching returned none
2021-08-13 19:06:42 [ WARN] rary/endpoint.cc(181): Replying with: device returned unparsable result, [%] has no match to input regex [RS=(?P<value_raw>.*)]
2021-08-14T17:44:56[INFO    ] dripline.core.endpoint(24) -> in get_request
2021-08-14T17:44:56[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07IP\r\n' -> '\x00\x07RS=FMR'
2021-08-14T17:44:56[ERROR   ] dripline.implementations.entity_endpoints(139) -> matching returned none
2021-08-13 19:06:42 [ WARN] rary/endpoint.cc(181): Replying with: device returned unparsable result, [RS=FMR] has no match to input regex [IP=(?P<value_raw>.*)]
2021-08-14T17:44:58[INFO    ] dripline.core.endpoint(24) -> in get_request
2021-08-14T17:44:58[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07IP\r\n' -> '\x00\x07IP=20815'
2021-08-14T17:45:10[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07ME\r\n' -> '\x00\x07IP=20815'
2021-08-14T17:45:13[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07AR\r\n\x00\x07WT1\r\n\x00\x07ME\r\n' -> '\x00\x07%'
2021-08-14T17:45:15[INFO    ] dripline.core.endpoint(24) -> in get_request
2021-08-14T17:45:15[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07IP\r\n' -> '\x00\x07%\r\x00\x07%\r\x00\x07*'
2021-08-14T17:45:15[ERROR   ] dripline.implementations.entity_endpoints(139) -> matching returned none
*] has no match to input regex [IP=(?P<value_raw>.*)]plying with: device returned unparsable result, [%
2021-08-14T17:45:18[INFO    ] dripline.core.endpoint(24) -> in get_request
2021-08-14T17:45:18[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07IP\r\n' -> '\x00\x07IP=20815'
2021-08-14T17:45:34[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07FP0\r\n' -> '\x00\x07IP=20815'
2021-08-14T17:45:34[INFO    ] dripline.core.endpoint(24) -> in get_request
2021-08-14T17:45:34[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07RS\r\n' -> '\x00\x07%'
2021-08-14T17:45:34[ERROR   ] dripline.implementations.entity_endpoints(139) -> matching returned none
2021-08-13 19:06:42 [ WARN] rary/endpoint.cc(181): Replying with: device returned unparsable result, [%] has no match to input regex [RS=(?P<value_raw>.*)]
2021-08-14T17:45:52[INFO    ] dripline.core.endpoint(24) -> in get_request
2021-08-14T17:45:52[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07IP\r\n' -> '\x00\x07RS=FMR'
2021-08-14T17:45:52[ERROR   ] dripline.implementations.entity_endpoints(139) -> matching returned none
2021-08-13 19:06:42 [ WARN] rary/endpoint.cc(181): Replying with: device returned unparsable result, [RS=FMR] has no match to input regex [IP=(?P<value_raw>.*)]
2021-08-14T17:45:54[INFO    ] dripline.core.endpoint(24) -> in get_request
2021-08-14T17:45:54[INFO    ] dripline.implementations.ethernet_scpi_service(172) -> sync: '\x00\x07IP\r\n' -> '\x00\x07IP=0'
```

**Comment by raphaelcervantes** [comment]
It's because dripline format entity doesn't correctly parse the output of some commands and then the dripline service crashes. Maybe we need something better than FormatEntity.
